name: main-latest

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *' # Scheduled runs every day at 3am UTC

jobs:

  git-trees:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache git worktree
        uses: actions/cache@v2
        with:
          path: /tmp/workdir/kernel/worktree
          key: ${{ runner.os }}-kernel-worktree-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-kernel-worktree

      - name: Prepare git trees, bulk of work
        run: |
          BASE_WORK_DIR="/tmp/workdir" bash shallow_kernel_tree.sh

      - name: "GH latest release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Linux kernel shallow git trees"
          files: |
            /tmp/workdir/kernel/output/*.gitshallow
            /tmp/workdir/kernel/output/*.gitbundle
            /tmp/workdir/kernel/output/*.git.tar

