name: main-latest

on:
  push:
    branches: [ main ]

jobs:

  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare release ID
        id: prep
        run: |
          echo ::set-output name=created::$(date -u +'%Y%m%d-%H%M')
    outputs:
      created: ${{ steps.prep.outputs.created }} # refer to as ${{needs.prepare.outputs.created}}


  build:
    needs: [ prepare ]
    runs-on: ubuntu-latest # soon to support hosted runners for arm64
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache git worktree
        uses: actions/cache@v2
        with:
          path: /tmp/workdir/kernel/worktree
          key: ${{ runner.os }}-kernel-worktree-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-kernel-worktree

      - name: Prepare git trees, bulk of work
        run: |
          BASE_WORK_DIR="/tmp/workdir" bash shallow_kernel_tree.sh


      - name: "GH latest release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest: ${{needs.prepare.outputs.created}}"
          files: |
            /tmp/workdir/output/*.gitshallow
            /tmp/workdir/output/*.gitbundle

